# Generated by Django 3.1.2 on 2023-06-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230607_2041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='db_carrito2',
        ),
    ]
